// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI4yi2l2sqbcemRgMf8jpqbzEgQ-ZesPU',
    appId: '1:612708400195:web:f0c2ec509ba1c78e3968f6',
    messagingSenderId: '612708400195',
    projectId: 'rittermicroblog',
    authDomain: 'rittermicroblog.firebaseapp.com',
    storageBucket: 'rittermicroblog.appspot.com',
    measurementId: 'G-KJW351B0FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH2nNDOno_gOy8O-uJhJEWYONtYW8mOhk',
    appId: '1:612708400195:android:f7d3501e81c5daeb3968f6',
    messagingSenderId: '612708400195',
    projectId: 'rittermicroblog',
    storageBucket: 'rittermicroblog.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBInX2QQMk9b0_ba5fDQeIfnQjWUxGxZag',
    appId: '1:612708400195:ios:3789abf5c53a2d223968f6',
    messagingSenderId: '612708400195',
    projectId: 'rittermicroblog',
    storageBucket: 'rittermicroblog.appspot.com',
    iosClientId: '612708400195-r15irro8idi680thot57u6roep8k1kbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ritterMicroblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBInX2QQMk9b0_ba5fDQeIfnQjWUxGxZag',
    appId: '1:612708400195:ios:3789abf5c53a2d223968f6',
    messagingSenderId: '612708400195',
    projectId: 'rittermicroblog',
    storageBucket: 'rittermicroblog.appspot.com',
    iosClientId: '612708400195-r15irro8idi680thot57u6roep8k1kbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ritterMicroblog',
  );
}
